/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftContent: typeof import('./src/components/selectOrgInfo/leftContent/index.vue')['default']
    MainContent: typeof import('./src/components/selectOrgInfo/mainContent.vue')['default']
    RightContent: typeof import('./src/components/selectOrgInfo/rightContent/index.vue')['default']
    SelectOrgInfo: typeof import('./src/components/selectOrgInfo/index.vue')['default']
  }
}
