/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/selectOrgInfo/listItem/avatar.vue')['default']
    Bread: typeof import('./src/components/selectOrgInfo/common/bread.vue')['default']
    Dept: typeof import('./src/components/selectOrgInfo/leftContent/dept.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftContent: typeof import('./src/components/selectOrgInfo/leftContent/index.vue')['default']
    ListItem: typeof import('./src/components/selectOrgInfo/listItem/index.vue')['default']
    ListPanel: typeof import('./src/components/selectOrgInfo/leftContent/listPanel.vue')['default']
    MainContent: typeof import('./src/components/selectOrgInfo/mainContent.vue')['default']
    Operate: typeof import('./src/components/selectOrgInfo/listItem/operate.vue')['default']
    Opetiosn: typeof import('./src/components/selectOrgInfo/listItem/opetiosn.vue')['default']
    RightContent: typeof import('./src/components/selectOrgInfo/rightContent/index.vue')['default']
    Role: typeof import('./src/components/selectOrgInfo/leftContent/role.vue')['default']
    SelectOrgInfo: typeof import('./src/components/selectOrgInfo/index.vue')['default']
    Staff: typeof import('./src/components/selectOrgInfo/leftContent/staff.vue')['default']
    Title: typeof import('./src/components/selectOrgInfo/listItem/title.vue')['default']
  }
}
